version: '3'

services:
  orion:
    image: fiware/orion:1.12.0
    ports:
      - "1026:1026"
    command: -logLevel ${ORION_LOG_LEVEL} -dbhost ${MONGO_SERVICE_URI} -rplSet ${REPLICASET_NAME} -dbTimeout 10000
    deploy:
      replicas: 2
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  # Legacy for running with docker-compose in FIWARE Lab
  default:
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_MTU}
  backend:
    driver: overlay
    external: true
  frontend:
    driver: overlay
    external: true
