version: '3.3'

services:
  mongo:
    image: mongo:3.2
    command: --nojournal
    networks:
      - backend

  iotagent:
    image: fiware/iotagent-ul:1.5.0
    entrypoint: "bin/iotagent-ul config.js"
    ports:
      # Agent HTTP transport port (Southbound)
      - "${IOTA_HTTP_PORT}:${IOTA_HTTP_PORT}"
      # Agent Northbound port
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}"
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
    configs:
      - source: iota-ul-conf
        target: /opt/iotaul/config.js
    networks:
      - backend

configs:
  iota-ul-conf:
    file: ./config.js

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_MTU}

  backend:
    external: true
