version: '3'

services:
  comet:
    image: telefonicaiot/fiware-sth-comet:2.2.0
    ports:
      - "8666:8666"
    deploy:
      replicas: 2
    environment:
      - STH_HOST=0.0.0.0
      - DB_URI=${MONGO_SERVICE_URI}
      - REPLICA_SET=${REPLICASET_NAME}
      - LOGOPS_LEVEL=DEBUG
    networks:
      - frontend
      - backend

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_MTU}
  frontend:
    driver: overlay
    external: true
  backend:
    driver: overlay
    external: true
